/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type LabelStruct = {
  key: PromiseOrValue<string>;
  value: PromiseOrValue<string>;
};

export type LabelStructOutput = [string, string] & {
  key: string;
  value: string;
};

export type JobDefinitionStruct = {
  gpuPerTask: PromiseOrValue<BigNumberish>;
  memPerCpu: PromiseOrValue<BigNumberish>;
  cpuPerTask: PromiseOrValue<BigNumberish>;
  ntasks: PromiseOrValue<BigNumberish>;
  batchLocationHash: PromiseOrValue<string>;
  storageType: PromiseOrValue<BigNumberish>;
  uses: LabelStruct[];
};

export type JobDefinitionStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  number,
  LabelStructOutput[]
] & {
  gpuPerTask: BigNumber;
  memPerCpu: BigNumber;
  cpuPerTask: BigNumber;
  ntasks: BigNumber;
  batchLocationHash: string;
  storageType: number;
  uses: LabelStructOutput[];
};

export type JobCostStruct = {
  maxCost: PromiseOrValue<BigNumberish>;
  finalCost: PromiseOrValue<BigNumberish>;
  pendingTopUp: PromiseOrValue<BigNumberish>;
  delegateSpendingAuthority: PromiseOrValue<boolean>;
};

export type JobCostStructOutput = [BigNumber, BigNumber, BigNumber, boolean] & {
  maxCost: BigNumber;
  finalCost: BigNumber;
  pendingTopUp: BigNumber;
  delegateSpendingAuthority: boolean;
};

export type JobTimeStruct = {
  start: PromiseOrValue<BigNumberish>;
  end: PromiseOrValue<BigNumberish>;
  cancelRequestTimestamp: PromiseOrValue<BigNumberish>;
  blockNumberStateChange: PromiseOrValue<BigNumberish>;
};

export type JobTimeStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  start: BigNumber;
  end: BigNumber;
  cancelRequestTimestamp: BigNumber;
  blockNumberStateChange: BigNumber;
};

export type JobStruct = {
  jobId: PromiseOrValue<BytesLike>;
  status: PromiseOrValue<BigNumberish>;
  customerAddr: PromiseOrValue<string>;
  providerAddr: PromiseOrValue<string>;
  definition: JobDefinitionStruct;
  valid: PromiseOrValue<boolean>;
  cost: JobCostStruct;
  time: JobTimeStruct;
  jobName: PromiseOrValue<BytesLike>;
  hasCancelRequest: PromiseOrValue<boolean>;
};

export type JobStructOutput = [
  string,
  number,
  string,
  string,
  JobDefinitionStructOutput,
  boolean,
  JobCostStructOutput,
  JobTimeStructOutput,
  string,
  boolean
] & {
  jobId: string;
  status: number;
  customerAddr: string;
  providerAddr: string;
  definition: JobDefinitionStructOutput;
  valid: boolean;
  cost: JobCostStructOutput;
  time: JobTimeStructOutput;
  jobName: string;
  hasCancelRequest: boolean;
};

export interface MetaSchedulerInterface extends utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "METASCHEDULER_ROLE()": FunctionFragment;
    "cancelJob(bytes32)": FunctionFragment;
    "claimJobTimeout()": FunctionFragment;
    "claimNextCancellingJob()": FunctionFragment;
    "claimNextJob()": FunctionFragment;
    "claimNextTopUpJob()": FunctionFragment;
    "credit()": FunctionFragment;
    "deepSquareBalance()": FunctionFragment;
    "getJob(bytes32)": FunctionFragment;
    "getJobs(address)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "hotJobList(uint256)": FunctionFragment;
    "jobIdCounter()": FunctionFragment;
    "jobs(bytes32)": FunctionFragment;
    "metaSchedule(bytes32,address)": FunctionFragment;
    "providerJobQueues()": FunctionFragment;
    "providerManager()": FunctionFragment;
    "providerSetJobStatus(bytes32,uint8,uint64)": FunctionFragment;
    "refuseJob(bytes32)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "requestNewJob((uint64,uint64,uint64,uint64,string,uint8,(string,string)[]),uint256,bytes32,bool)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setDelegateSpendingAuthority(bytes32,bool)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "topUpJob(bytes32,uint256)": FunctionFragment;
    "topUpJobDelegate(bytes32)": FunctionFragment;
    "wallet2JobId(address,uint256)": FunctionFragment;
    "withdrawAdmin(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEFAULT_ADMIN_ROLE"
      | "METASCHEDULER_ROLE"
      | "cancelJob"
      | "claimJobTimeout"
      | "claimNextCancellingJob"
      | "claimNextJob"
      | "claimNextTopUpJob"
      | "credit"
      | "deepSquareBalance"
      | "getJob"
      | "getJobs"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "hotJobList"
      | "jobIdCounter"
      | "jobs"
      | "metaSchedule"
      | "providerJobQueues"
      | "providerManager"
      | "providerSetJobStatus"
      | "refuseJob"
      | "renounceRole"
      | "requestNewJob"
      | "revokeRole"
      | "setDelegateSpendingAuthority"
      | "supportsInterface"
      | "topUpJob"
      | "topUpJobDelegate"
      | "wallet2JobId"
      | "withdrawAdmin"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "METASCHEDULER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelJob",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimJobTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimNextCancellingJob",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimNextJob",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimNextTopUpJob",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "credit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deepSquareBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobs",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hotJobList",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "jobIdCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "jobs",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "metaSchedule",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "providerJobQueues",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "providerManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "providerSetJobStatus",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "refuseJob",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "requestNewJob",
    values: [
      JobDefinitionStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setDelegateSpendingAuthority",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "topUpJob",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "topUpJobDelegate",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "wallet2JobId",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAdmin",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "METASCHEDULER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimJobTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimNextCancellingJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimNextJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimNextTopUpJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "credit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deepSquareBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hotJobList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "jobIdCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "metaSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerJobQueues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerSetJobStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refuseJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestNewJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDelegateSpendingAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "topUpJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "topUpJobDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wallet2JobId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAdmin",
    data: BytesLike
  ): Result;

  events: {
    "BilledTooMuchEvent(bytes32,address,uint256)": EventFragment;
    "ClaimJobEvent(address,address,bytes32,uint64,tuple)": EventFragment;
    "ClaimNextCancellingJobEvent(address,address,bytes32)": EventFragment;
    "ClaimNextTopUpJobEvent(bytes32,address,uint64)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "JobRefusedEvent(bytes32,address,address)": EventFragment;
    "JobTransitionEvent(bytes32,uint8,uint8)": EventFragment;
    "NewJobRequestEvent(bytes32,address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BilledTooMuchEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimJobEvent"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ClaimNextCancellingJobEvent"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimNextTopUpJobEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "JobRefusedEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "JobTransitionEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewJobRequestEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
}

export interface BilledTooMuchEventEventObject {
  _jobId: string;
  _providerAddr: string;
  _billingAmount: BigNumber;
}
export type BilledTooMuchEventEvent = TypedEvent<
  [string, string, BigNumber],
  BilledTooMuchEventEventObject
>;

export type BilledTooMuchEventEventFilter =
  TypedEventFilter<BilledTooMuchEventEvent>;

export interface ClaimJobEventEventObject {
  customerAddr: string;
  providerAddr: string;
  jobId: string;
  maxDurationMinute: BigNumber;
  jobDefinition: JobDefinitionStructOutput;
}
export type ClaimJobEventEvent = TypedEvent<
  [string, string, string, BigNumber, JobDefinitionStructOutput],
  ClaimJobEventEventObject
>;

export type ClaimJobEventEventFilter = TypedEventFilter<ClaimJobEventEvent>;

export interface ClaimNextCancellingJobEventEventObject {
  customerAddr: string;
  providerAddr: string;
  jobId: string;
}
export type ClaimNextCancellingJobEventEvent = TypedEvent<
  [string, string, string],
  ClaimNextCancellingJobEventEventObject
>;

export type ClaimNextCancellingJobEventEventFilter =
  TypedEventFilter<ClaimNextCancellingJobEventEvent>;

export interface ClaimNextTopUpJobEventEventObject {
  _jobId: string;
  _providerAddr: string;
  maxDurationMinute: BigNumber;
}
export type ClaimNextTopUpJobEventEvent = TypedEvent<
  [string, string, BigNumber],
  ClaimNextTopUpJobEventEventObject
>;

export type ClaimNextTopUpJobEventEventFilter =
  TypedEventFilter<ClaimNextTopUpJobEventEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface JobRefusedEventEventObject {
  _jobId: string;
  _providerAddr: string;
  _customerAddr: string;
}
export type JobRefusedEventEvent = TypedEvent<
  [string, string, string],
  JobRefusedEventEventObject
>;

export type JobRefusedEventEventFilter = TypedEventFilter<JobRefusedEventEvent>;

export interface JobTransitionEventEventObject {
  _jobId: string;
  _from: number;
  _to: number;
}
export type JobTransitionEventEvent = TypedEvent<
  [string, number, number],
  JobTransitionEventEventObject
>;

export type JobTransitionEventEventFilter =
  TypedEventFilter<JobTransitionEventEvent>;

export interface NewJobRequestEventEventObject {
  _jobId: string;
  _customerAddr: string;
}
export type NewJobRequestEventEvent = TypedEvent<
  [string, string],
  NewJobRequestEventEventObject
>;

export type NewJobRequestEventEventFilter =
  TypedEventFilter<NewJobRequestEventEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface MetaScheduler extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MetaSchedulerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    METASCHEDULER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    cancelJob(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimJobTimeout(overrides?: CallOverrides): Promise<[BigNumber]>;

    claimNextCancellingJob(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimNextJob(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimNextTopUpJob(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    credit(overrides?: CallOverrides): Promise<[string]>;

    deepSquareBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    getJob(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[JobStructOutput]>;

    getJobs(
      walletAddr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    hotJobList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    jobIdCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    jobs(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        number,
        string,
        string,
        JobDefinitionStructOutput,
        boolean,
        JobCostStructOutput,
        JobTimeStructOutput,
        string,
        boolean
      ] & {
        jobId: string;
        status: number;
        customerAddr: string;
        providerAddr: string;
        definition: JobDefinitionStructOutput;
        valid: boolean;
        cost: JobCostStructOutput;
        time: JobTimeStructOutput;
        jobName: string;
        hasCancelRequest: boolean;
      }
    >;

    metaSchedule(
      _jobId: PromiseOrValue<BytesLike>,
      _providerAddr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    providerJobQueues(overrides?: CallOverrides): Promise<[string]>;

    providerManager(overrides?: CallOverrides): Promise<[string]>;

    providerSetJobStatus(
      _jobId: PromiseOrValue<BytesLike>,
      _nextJobStatus: PromiseOrValue<BigNumberish>,
      _jobDurationMinute: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    refuseJob(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requestNewJob(
      _definition: JobDefinitionStruct,
      _lockedCredits: PromiseOrValue<BigNumberish>,
      _jobName: PromiseOrValue<BytesLike>,
      _delegateSpendingAuthority: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDelegateSpendingAuthority(
      _jobId: PromiseOrValue<BytesLike>,
      _delegateSpendingAuthority: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    topUpJob(
      _jobId: PromiseOrValue<BytesLike>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    topUpJobDelegate(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wallet2JobId(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    withdrawAdmin(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  METASCHEDULER_ROLE(overrides?: CallOverrides): Promise<string>;

  cancelJob(
    _jobId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimJobTimeout(overrides?: CallOverrides): Promise<BigNumber>;

  claimNextCancellingJob(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimNextJob(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimNextTopUpJob(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  credit(overrides?: CallOverrides): Promise<string>;

  deepSquareBalance(overrides?: CallOverrides): Promise<BigNumber>;

  getJob(
    _jobId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<JobStructOutput>;

  getJobs(
    walletAddr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getRoleAdmin(
    role: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  grantRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  hotJobList(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  jobIdCounter(overrides?: CallOverrides): Promise<BigNumber>;

  jobs(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      number,
      string,
      string,
      JobDefinitionStructOutput,
      boolean,
      JobCostStructOutput,
      JobTimeStructOutput,
      string,
      boolean
    ] & {
      jobId: string;
      status: number;
      customerAddr: string;
      providerAddr: string;
      definition: JobDefinitionStructOutput;
      valid: boolean;
      cost: JobCostStructOutput;
      time: JobTimeStructOutput;
      jobName: string;
      hasCancelRequest: boolean;
    }
  >;

  metaSchedule(
    _jobId: PromiseOrValue<BytesLike>,
    _providerAddr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  providerJobQueues(overrides?: CallOverrides): Promise<string>;

  providerManager(overrides?: CallOverrides): Promise<string>;

  providerSetJobStatus(
    _jobId: PromiseOrValue<BytesLike>,
    _nextJobStatus: PromiseOrValue<BigNumberish>,
    _jobDurationMinute: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  refuseJob(
    _jobId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requestNewJob(
    _definition: JobDefinitionStruct,
    _lockedCredits: PromiseOrValue<BigNumberish>,
    _jobName: PromiseOrValue<BytesLike>,
    _delegateSpendingAuthority: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDelegateSpendingAuthority(
    _jobId: PromiseOrValue<BytesLike>,
    _delegateSpendingAuthority: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  topUpJob(
    _jobId: PromiseOrValue<BytesLike>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  topUpJobDelegate(
    _jobId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wallet2JobId(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  withdrawAdmin(
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    METASCHEDULER_ROLE(overrides?: CallOverrides): Promise<string>;

    cancelJob(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimJobTimeout(overrides?: CallOverrides): Promise<BigNumber>;

    claimNextCancellingJob(overrides?: CallOverrides): Promise<void>;

    claimNextJob(overrides?: CallOverrides): Promise<void>;

    claimNextTopUpJob(overrides?: CallOverrides): Promise<void>;

    credit(overrides?: CallOverrides): Promise<string>;

    deepSquareBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getJob(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<JobStructOutput>;

    getJobs(
      walletAddr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hotJobList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    jobIdCounter(overrides?: CallOverrides): Promise<BigNumber>;

    jobs(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        number,
        string,
        string,
        JobDefinitionStructOutput,
        boolean,
        JobCostStructOutput,
        JobTimeStructOutput,
        string,
        boolean
      ] & {
        jobId: string;
        status: number;
        customerAddr: string;
        providerAddr: string;
        definition: JobDefinitionStructOutput;
        valid: boolean;
        cost: JobCostStructOutput;
        time: JobTimeStructOutput;
        jobName: string;
        hasCancelRequest: boolean;
      }
    >;

    metaSchedule(
      _jobId: PromiseOrValue<BytesLike>,
      _providerAddr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    providerJobQueues(overrides?: CallOverrides): Promise<string>;

    providerManager(overrides?: CallOverrides): Promise<string>;

    providerSetJobStatus(
      _jobId: PromiseOrValue<BytesLike>,
      _nextJobStatus: PromiseOrValue<BigNumberish>,
      _jobDurationMinute: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    refuseJob(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    requestNewJob(
      _definition: JobDefinitionStruct,
      _lockedCredits: PromiseOrValue<BigNumberish>,
      _jobName: PromiseOrValue<BytesLike>,
      _delegateSpendingAuthority: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<string>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDelegateSpendingAuthority(
      _jobId: PromiseOrValue<BytesLike>,
      _delegateSpendingAuthority: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    topUpJob(
      _jobId: PromiseOrValue<BytesLike>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    topUpJobDelegate(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    wallet2JobId(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    withdrawAdmin(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BilledTooMuchEvent(bytes32,address,uint256)"(
      _jobId?: null,
      _providerAddr?: null,
      _billingAmount?: null
    ): BilledTooMuchEventEventFilter;
    BilledTooMuchEvent(
      _jobId?: null,
      _providerAddr?: null,
      _billingAmount?: null
    ): BilledTooMuchEventEventFilter;

    "ClaimJobEvent(address,address,bytes32,uint64,tuple)"(
      customerAddr?: null,
      providerAddr?: null,
      jobId?: null,
      maxDurationMinute?: null,
      jobDefinition?: null
    ): ClaimJobEventEventFilter;
    ClaimJobEvent(
      customerAddr?: null,
      providerAddr?: null,
      jobId?: null,
      maxDurationMinute?: null,
      jobDefinition?: null
    ): ClaimJobEventEventFilter;

    "ClaimNextCancellingJobEvent(address,address,bytes32)"(
      customerAddr?: null,
      providerAddr?: null,
      jobId?: null
    ): ClaimNextCancellingJobEventEventFilter;
    ClaimNextCancellingJobEvent(
      customerAddr?: null,
      providerAddr?: null,
      jobId?: null
    ): ClaimNextCancellingJobEventEventFilter;

    "ClaimNextTopUpJobEvent(bytes32,address,uint64)"(
      _jobId?: null,
      _providerAddr?: null,
      maxDurationMinute?: null
    ): ClaimNextTopUpJobEventEventFilter;
    ClaimNextTopUpJobEvent(
      _jobId?: null,
      _providerAddr?: null,
      maxDurationMinute?: null
    ): ClaimNextTopUpJobEventEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "JobRefusedEvent(bytes32,address,address)"(
      _jobId?: null,
      _providerAddr?: null,
      _customerAddr?: null
    ): JobRefusedEventEventFilter;
    JobRefusedEvent(
      _jobId?: null,
      _providerAddr?: null,
      _customerAddr?: null
    ): JobRefusedEventEventFilter;

    "JobTransitionEvent(bytes32,uint8,uint8)"(
      _jobId?: null,
      _from?: null,
      _to?: null
    ): JobTransitionEventEventFilter;
    JobTransitionEvent(
      _jobId?: null,
      _from?: null,
      _to?: null
    ): JobTransitionEventEventFilter;

    "NewJobRequestEvent(bytes32,address)"(
      _jobId?: null,
      _customerAddr?: null
    ): NewJobRequestEventEventFilter;
    NewJobRequestEvent(
      _jobId?: null,
      _customerAddr?: null
    ): NewJobRequestEventEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    METASCHEDULER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    cancelJob(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimJobTimeout(overrides?: CallOverrides): Promise<BigNumber>;

    claimNextCancellingJob(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimNextJob(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimNextTopUpJob(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    credit(overrides?: CallOverrides): Promise<BigNumber>;

    deepSquareBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getJob(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getJobs(
      walletAddr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hotJobList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    jobIdCounter(overrides?: CallOverrides): Promise<BigNumber>;

    jobs(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    metaSchedule(
      _jobId: PromiseOrValue<BytesLike>,
      _providerAddr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    providerJobQueues(overrides?: CallOverrides): Promise<BigNumber>;

    providerManager(overrides?: CallOverrides): Promise<BigNumber>;

    providerSetJobStatus(
      _jobId: PromiseOrValue<BytesLike>,
      _nextJobStatus: PromiseOrValue<BigNumberish>,
      _jobDurationMinute: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    refuseJob(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requestNewJob(
      _definition: JobDefinitionStruct,
      _lockedCredits: PromiseOrValue<BigNumberish>,
      _jobName: PromiseOrValue<BytesLike>,
      _delegateSpendingAuthority: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDelegateSpendingAuthority(
      _jobId: PromiseOrValue<BytesLike>,
      _delegateSpendingAuthority: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    topUpJob(
      _jobId: PromiseOrValue<BytesLike>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    topUpJobDelegate(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wallet2JobId(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawAdmin(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    METASCHEDULER_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelJob(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimJobTimeout(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimNextCancellingJob(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimNextJob(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimNextTopUpJob(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    credit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deepSquareBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getJob(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getJobs(
      walletAddr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hotJobList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    jobIdCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    jobs(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    metaSchedule(
      _jobId: PromiseOrValue<BytesLike>,
      _providerAddr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    providerJobQueues(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    providerManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    providerSetJobStatus(
      _jobId: PromiseOrValue<BytesLike>,
      _nextJobStatus: PromiseOrValue<BigNumberish>,
      _jobDurationMinute: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    refuseJob(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requestNewJob(
      _definition: JobDefinitionStruct,
      _lockedCredits: PromiseOrValue<BigNumberish>,
      _jobName: PromiseOrValue<BytesLike>,
      _delegateSpendingAuthority: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDelegateSpendingAuthority(
      _jobId: PromiseOrValue<BytesLike>,
      _delegateSpendingAuthority: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    topUpJob(
      _jobId: PromiseOrValue<BytesLike>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    topUpJobDelegate(
      _jobId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wallet2JobId(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawAdmin(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
