name: Node CI

on:
  push:
    branches:
      - main
  release:
    # This specifies that the build will be triggered when we publish a release
    types: [published]
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint

  build:
    name: Build
    runs-on: ubuntu-latest

    needs: [lint]

    steps:
      - name: Checkout code
        if: ${{ github.event_name != 'release' }}
        uses: actions/checkout@v4

      - name: Checkout code to branch
        uses: actions/checkout@v4
        if: ${{ github.event_name == 'release' }}
        with:
          ref: ${{ github.event.release.target_commitish }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run build
        run: bun run build

      - name: Git configuration
        if: ${{ github.event_name == 'release' }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Bump version and retag
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -d ${{ github.event.release.tag_name }}
          git push origin --delete ${{ github.event.release.tag_name }}
          npm version ${{ github.event.release.tag_name }} --allow-same-version
          git push origin ${{ github.event.release.tag_name }} --tags

      - name: Publish
        if: ${{ github.event_name == 'release' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          export TAG_NAME="${{ github.event.release.tag_name }}"
          TAG=$(node -e 'console.log(process.env.TAG_NAME.includes("-rc") || process.env.TAG_NAME.includes("-beta") || process.env.TAG_NAME.includes("-alpha") ? "next" : "latest")')
          npm publish --tag $TAG
