name: Node CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint

  build:
    name: Build
    runs-on: ubuntu-latest

    needs: [lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run build
        run: bun run build

      - name: Git configuration
        if: startsWith(github.ref, 'refs/tags')
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Bump version and retag
        if: startsWith(github.ref, 'refs/tags')
        run: |
          GIT_TAG=$(echo $GITHUB_REF | cut -d '/' -f 3)
          git tag -d $GIT_TAG
          git push origin --delete $GIT_TAG
          npm version $GIT_TAG --allow-same-version

      - name: Push changes to repository
        if: startsWith(github.ref, 'refs/tags')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin && git push --tags

      - name: Publish
        if: startsWith(github.ref, 'refs/tags')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          TAG=$(node -e 'console.log(process.env.GITHUB_REF.includes("-rc") || process.env.GITHUB_REF.includes("-beta") || process.env.GITHUB_REF.includes("-alpha") ? "next" : "latest")')
          npm publish --tag $TAG
